version: "3.9"

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.6
    container_name: elasticsearch
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
    ports:
      - 9200:9200
      - 9300:9300
    volumes:
      - elasticsearch-data:/var/lib/elasticsearch/data

  postgres:
    image: postgres:14.2
    environment:
      POSTGRES_USER: black_yeti
      POSTGRES_PASSWORD: black_yeti
    ports:
      - '5432:5432'
    volumes:
      - black-yeti-postgres:/var/lib/postgresql/data

  redis:
    image: redis:7.0
    ports:
      - '6379:6379'
    volumes:
      - black-yeti-redis:/var/lib/redis/data

  sidekiq:
    build:
      context: .
    command: bundle exec sidekiq
    links:
      - postgres
      - redis
    env_file:
      - .env

  web:
    build:
      context: .
    volumes:
      - ./black_yeti:/opt/app
    links:
      - postgres
      - redis
      - elasticsearch:elasticsearch
    ports:
      - '8010:8010'
    env_file:
      - .env
    stdin_open: true
    tty: true

  # nginx:
  #   build:
  #     context: .
  #     dockerfile: ./Dockerfile.nginx
  #   links:
  #     - web
  #   ports:
  #     - '8020:8020'

volumes:
  black-yeti-postgres:
  black-yeti-redis:
  elasticsearch-data:
    driver: local
